In [18]:
# libraries
import numpy as np
#from io import StringIO

### Input Data

In [44]:
# load dataset
dataset=np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', encoding='ascii', usecols=(0,1,2,3,4))
features =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=None, delimiter=',', encoding='ascii', usecols=(0,1,2,3))
targets =np.loadtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype="U", delimiter=',', encoding='ascii', usecols=(4))
print('type: ', features.dtype)
print('size: ', features.shape)
print()
print("first 10 values of the dataset: ", "\n",dataset[:10,:])
print()
print("first 10 values of the features: ", "\n",features[:10,:])
print()
print("first 10 targets: ", "\n", targets[:10])


type:  float64
size:  (150, 4)

first 10 values of the dataset:  
 [[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]]

first 10 values of the features:  
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

first 10 targets:  
 ['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


### 1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [47]:
T=dataset[:,4]
print(T[:10])

[nan nan nan nan nan nan nan nan nan nan]


### 2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [56]:
features2d = np.array(features)
print(features2d[1:10,:])
print('Num Dimensions: ', features2d.ndim)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
Num Dimensions:  2


### 3. Порахувати mean, median, standard deviation для 1-ї колонки

In [60]:
print('Mean value: ',round(features[:,0].mean(),2))
print('Median value: ', np.median(features[:,0]))
print('Standard deviation: ', round(features[:,0].std(),2))

Mean value:  5.84
Median value:  5.8
Standard deviation:  0.83


### 4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [91]:
a = np.random.choice(range(features.shape[0]), 20, replace=False)
x = np.random.choice(range(features.shape[0]), 10, replace=False)
y = np.random.choice(range(features.shape[1]), 10)

print('unique 20 positions in the first column: ', sorted(a))
print('unique 10 positions in the first column: ', x)
print('10 random positions in the row: ', y)

# change 20 random values in the first column
features_nan_1=features.copy()
features_nan_1[a,0]=np.nan
# print("20 random positions with nan in 1st column: "features_nan)


# change 20 random position in the matrix of the features
features_nan_2=features.copy()
features_nan_2[x,y]=np.nan
#print(features_nan_2)

unique 20 positions in the first column:  [9, 10, 21, 32, 33, 44, 53, 68, 74, 84, 92, 103, 107, 116, 126, 127, 135, 136, 144, 148]
unique 10 positions in the first column:  [140  87  72 146  18 112  20  41  49  86]
10 random positions in the row:  [0 0 0 2 2 2 0 0 0 3]


### 5. Знайти позиції вставлених значень np.nan в 1-й колонці

In [92]:
print("Case when 20 nandom positions were selected in the fisrst column: ", '\n',np.argwhere(np.isnan(features_nan_1[:,0])))
print()
print("Case when 20 random positions were selected in the whole matrix: ", '\n', np.argwhere(np.isnan(features_nan_2[:,0])))

Case when 20 nandom positions were selected in the fisrst column:  
 [[  9]
 [ 10]
 [ 21]
 [ 32]
 [ 33]
 [ 44]
 [ 53]
 [ 68]
 [ 74]
 [ 84]
 [ 92]
 [103]
 [107]
 [116]
 [126]
 [127]
 [135]
 [136]
 [144]
 [148]]

Case when 20 random positions were selected in the whole matrix:  
 [[ 20]
 [ 41]
 [ 49]
 [ 72]
 [ 87]
 [140]]


### 6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [102]:
ind=np.where((features[:,2]>1.5) & (features[:,0]<5))
features_filtered=features[ind,:]
print(features_filtered)

[[[4.8 3.4 1.6 0.2]
  [4.8 3.4 1.9 0.2]
  [4.7 3.2 1.6 0.2]
  [4.8 3.1 1.6 0.2]
  [4.9 2.4 3.3 1. ]
  [4.9 2.5 4.5 1.7]]]


### 7. Замінити всі значення np.nan на 0

In [112]:
features_0=features_nan_1.copy()
features_0[np.isnan(features_0)] = 0

print(features_nan_1[:10,:])
print()
print(features_0[:10,:])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [nan 3.1 1.5 0.1]]

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [0.  3.1 1.5 0.1]]


### 8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

In [125]:
unique, counts = np.unique(features, return_counts=True)

print("unique values in the array <features>: ", '\n',unique)
print()
print("number of the unique values appiarance: ", '\n',counts)

unique values in the array <features>:  
 [0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9
 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6
 7.7 7.9]

number of the unique values appiarance:  
 [ 6 28  7  7  1  1  8  4  7 20 20 26 11  6 12  7  7  6  6 12  6 11  5  9
 14 10 27 12 13  8 12  8  4  4  7  5  6  4  5  3  8  9  7  7  9 11 14 17
  6  3  8 10 12 11 10  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1  1
  4  1]


### 9. Розбити масив по горизонталі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [155]:
ind=round(features.shape[0]/2)
features1=features[:ind,:]
features2=features[ind:,:]
print('detected index:',ind)
print("first half: ",features1.shape)
print("second half: ",features1.shape)

detected index: 75
first half:  (75, 4)
second half:  (75, 4)


### 10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [156]:
ind1 = np.argsort(features1[:,0])
features1_sorted=features1[ind1]


ind2 = np.argsort(features2[:,0])[::-1]
features2_sorted=features2[ind2]


print('sorted first half: ','\n', features1_sorted[:10])
print()
print('sorted second half: ','\n',features2_sorted[:10])


sorted first half:  
 [[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]]

sorted second half:  
 [[7.9 3.8 6.4 2. ]
 [7.7 2.8 6.7 2. ]
 [7.7 2.6 6.9 2.3]
 [7.7 3.8 6.7 2.2]
 [7.7 3.  6.1 2.3]
 [7.6 3.  6.6 2.1]
 [7.4 2.8 6.1 1.9]
 [7.3 2.9 6.3 1.8]
 [7.2 3.  5.8 1.6]
 [7.2 3.6 6.1 2.5]]


### 11. Зібрати обидва массиви в одне ціле

In [157]:
features_concat=np.concatenate([features1, features2], axis=0)
print(features_concat.shape)
print(features_concat[:10])

(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


### 12. Знайти найбільш часто повторюване значення в массиві

In [167]:
unique, counts = np.unique(features, return_counts=True)
ind=np.argmax(counts, axis=0)
print(counts)
print()
print(unique)
print()
print('the most common value: ', unique[ind])

[ 6 28  7  7  1  1  8  4  7 20 20 26 11  6 12  7  7  6  6 12  6 11  5  9
 14 10 27 12 13  8 12  8  4  4  7  5  6  4  5  3  8  9  7  7  9 11 14 17
  6  3  8 10 12 11 10  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1  1
  4  1]

[0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9
 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6
 7.7 7.9]

the most common value:  0.2


### 13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [240]:
def myfunc(x):
    xx=x.copy()
    if x.ndim>1:
        for i in range(x.shape[0]):
            xx[np.where(x[:,i]<(x[:,i].mean())),i] *=2
            xx[np.where(x[:,i]>=(x[:,i].mean())),i] *=0.25
    elif x.ndim==1:
            xx[np.where(x<(x.mean()))] *=2
            xx[np.where(x>=(x.mean()))] *=0.25
    return xx

In [241]:
x = np.array([[4,1,1], [1,0,4], [1,1,2]]).astype('float32')
print('Input array: ','\n', x)
print('Processed array: ', '\n', myfunc(x))

Input array:  
 [[4. 1. 1.]
 [1. 0. 4.]
 [1. 1. 2.]]
Processed array:  
 [[1.   0.25 2.  ]
 [2.   0.   1.  ]
 [2.   0.25 4.  ]]


### 14. Застосувати отриману функцію до 3-ї колонки

In [243]:
x = np.array([[4,1,1], [1,0,4], [1,1,2]]).astype('float32')

print(myfunc(x[:,2]))

[2. 1. 4.]
